inputs:
  branch: 
    description: 'Code branch to init action'
    default: 'main'
  remote_directory: 
    description: 'Destination of files in remote server'
    default: '/home/bitnami/apps/react-cicd-test/build/'    

name: deploy_to_env

on:
  push:
    branches:
      - ${{ inputs.branch }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm i
      - run: npm run build
      
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./build/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ input.remote_directory }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
