name: MasterCI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy@v1
        with: 
          branch: main
          remote_directory: /home/bitnami/apps/react-cicd-test/build